# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(default='', max_length=300)),
                ('ITI', models.DecimalField(decimal_places=3, max_digits=5)),
                ('TR', models.DecimalField(decimal_places=3, max_digits=5)),
                ('L', models.IntegerField()),
                ('S', models.IntegerField()),
                ('C', models.CharField(default='', max_length=300)),
                ('P', models.CharField(default='', max_length=300)),
                ('rho', models.DecimalField(decimal_places=3, default=0.3, max_digits=5)),
                ('W1', models.DecimalField(decimal_places=3, default=0.25, max_digits=5)),
                ('W2', models.DecimalField(decimal_places=3, default=0.25, max_digits=5)),
                ('W3', models.DecimalField(decimal_places=3, default=0.25, max_digits=5)),
                ('W4', models.DecimalField(decimal_places=3, default=0.25, max_digits=5)),
                ('Aoptimality', models.IntegerField(choices=[(1, 'A-optimality'), (2, 'D-optimality')], default=1)),
                ('Saturation', models.IntegerField(choices=[(1, 'Saturation'), (2, 'No Saturation')], default=1)),
                ('resolution', models.DecimalField(decimal_places=3, default=0.1, max_digits=5)),
                ('G', models.IntegerField(default=20)),
                ('q', models.DecimalField(decimal_places=3, default=0.01, max_digits=5)),
                ('I', models.IntegerField(default=4)),
                ('cycles', models.IntegerField(default=50)),
                ('preruncycles', models.IntegerField(default=10)),
                ('ConfoundOrder', models.IntegerField(default=3)),
                ('MaxRepeat', models.IntegerField(default=6)),
            ],
        ),
    ]
