# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-22 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='conpars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='mainpars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='nestpars',
            field=models.BooleanField(default=False),
        ),
    ]
