# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='Clen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
