# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='C00',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C01',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C02',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C03',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C04',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C05',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C06',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C07',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C08',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C09',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C10',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C11',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C12',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C13',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C14',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C15',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C16',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C17',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C18',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C19',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C20',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C21',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C22',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C23',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C24',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C25',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C26',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C27',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C28',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C29',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C30',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C31',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C32',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C33',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C34',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C35',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C36',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C37',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C38',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C39',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C40',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C41',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C42',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C43',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C44',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C45',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C46',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C47',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C48',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='C49',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='Clen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P0',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P3',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P4',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P5',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P6',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P7',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P8',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='P9',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='C',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='ITI',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='L',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='P',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='S',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='TR',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='W1',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='W2',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='W3',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='W4',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='q',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='resolution',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='rho',
            field=models.FloatField(default=0.3),
        ),
    ]
