# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-22 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0002_auto_20170222_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='conpars',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='mainpars',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='nestpars',
            field=models.NullBooleanField(default=False),
        ),
    ]
