# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0003_auto_20170222_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
