# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 22:10
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0005_designmodel_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='optimal',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
