# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0006_auto_20160804_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='Clen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='L',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='S',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
