# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0007_designmodel_hardprob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='HardProb',
            field=models.BooleanField(default=False),
        ),
    ]
