# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0008_auto_20160820_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='ITImax',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='ITImin',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
