# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 01:54
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0009_auto_20160825_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designmodel',
            old_name='optimal',
            new_name='optimalonsets',
        ),
        migrations.AddField(
            model_name='designmodel',
            name='optimalorder',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
