# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0010_auto_20160826_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='conpars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='mainpars',
            field=models.BooleanField(default=False),
        ),
    ]
