# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0011_auto_20160829_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='Call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='Clen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
