# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0013_auto_20160901_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='cycles',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='preruncycles',
            field=models.IntegerField(default=50),
        ),
    ]
