# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0014_auto_20160904_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='cycles',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='preruncycles',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='resolution',
            field=models.FloatField(default=0.25),
        ),
    ]
