# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0015_auto_20160905_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='W1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='W2',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='cycles',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='preruncycles',
            field=models.IntegerField(default=10),
        ),
    ]
