# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0016_auto_20160907_1914'),
        ('designtoolbox', '0016_auto_20160905_2201'),
    ]

    operations = [
    ]
