# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='done',
            field=models.IntegerField(default=0),
        ),
    ]
