# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0018_designmodel_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='ITImean',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
