# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0019_designmodel_itimean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='RestDur',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
