# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0020_auto_20160914_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='nest_classes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='nest_structure',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='nested',
            field=models.BooleanField(default=False),
        ),
    ]
