# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0024_designmodel_nest_symmetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='nestpars',
            field=models.BooleanField(default=False),
        ),
    ]
