# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 21:06
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0026_designmodel_stim_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='desfile',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='genfile',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='onsetsfolder',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
