# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0027_auto_20160917_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='shareID',
            field=models.CharField(default='', max_length=300),
        ),
    ]
