# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0029_auto_20160921_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designmodel',
            name='done',
        ),
        migrations.RemoveField(
            model_name='designmodel',
            name='stop',
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='taskstatus',
            field=models.IntegerField(default=0),
        ),
    ]
