# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0032_auto_20160924_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
