# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0033_designmodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='duration_seconds',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='duration_unit',
            field=models.IntegerField(choices=[(1, 'seconds'), (2, 'minutes')], default=2),
        ),
    ]
