# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0034_auto_20161021_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designmodel',
            old_name='duration_seconds',
            new_name='duration_unitfree',
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
