# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-22 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0035_auto_20161021_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='durspec',
            field=models.IntegerField(choices=[(1, 'duration'), (2, 'trial count')], default=1),
            preserve_default=False,
        ),
    ]
