# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-22 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0036_designmodel_durspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='durspec',
            field=models.IntegerField(choices=[(1, 'duration'), (2, 'trial count')], default=1),
        ),
    ]
