# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-22 19:06
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0038_auto_20161022_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='optimalitis',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
