# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0039_designmodel_optimalitis'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='cmd',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='designoutput',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='file',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='zip_filename',
            field=models.CharField(default='', max_length=300),
        ),
    ]
