# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-08 19:57
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0040_auto_20161107_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='codefile',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
