# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-08 20:14
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0041_designmodel_codefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='codefilename',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
