# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-16 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0042_designmodel_codefilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='statusfile',
            field=models.CharField(default='', max_length=500),
        ),
    ]
