# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-16 06:54
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0043_designmodel_statusfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='designmodel',
            name='zipfile',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
