# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-16 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0044_auto_20161116_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='seed',
            field=models.IntegerField(default=1),
        ),
    ]
