# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 19:32
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0046_auto_20161116_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designmodel',
            old_name='onsetsfolder',
            new_name='bestdesign',
        ),
        migrations.AddField(
            model_name='designmodel',
            name='design_suffix',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='files',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='local_folder',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='metrics',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='onsets_folder',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
