# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0047_auto_20170112_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='designmodel',
            name='outdes',
            field=models.IntegerField(default=3),
        ),
    ]
