# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-09 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designtoolbox', '0048_designmodel_outdes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designmodel',
            old_name='statusfile',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='designmodel',
            name='desfile',
        ),
        migrations.RemoveField(
            model_name='designmodel',
            name='designoutput',
        ),
        migrations.RemoveField(
            model_name='designmodel',
            name='genfile',
        ),
        migrations.RemoveField(
            model_name='designmodel',
            name='optimalitis',
        ),
        migrations.RemoveField(
            model_name='designmodel',
            name='optimalonsets',
        ),
        migrations.RemoveField(
            model_name='designmodel',
            name='optimalorder',
        ),
        migrations.AddField(
            model_name='designmodel',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='generation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='designmodel',
            name='timestart',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='designmodel',
            name='outdes',
            field=models.IntegerField(default=1),
        ),
    ]
