# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('neuropowertoolbox', '0010_auto_20160217_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='niftimodel',
            name='sessionKey',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
