# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('neuropowertoolbox', '0014_niftimodel_sessid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niftimodel',
            name='sessID',
        ),
        migrations.AddField(
            model_name='niftimodel',
            name='SID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
