# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0017_parametermodel_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaktablemodel',
            name='SID',
            field=models.CharField(default='', max_length=300),
        ),
    ]
