# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0018_peaktablemodel_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixtureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(default='', max_length=300)),
                ('pi1', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mu', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sigma', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
