# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0019_mixturemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametermodel',
            name='DoF',
            field=models.DecimalField(decimal_places=2, default='NaN', max_digits=5),
        ),
        migrations.AddField(
            model_name='parametermodel',
            name='ExcZ',
            field=models.DecimalField(decimal_places=2, default='NaN', max_digits=5),
        ),
    ]
