# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0021_mixturemodel_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(default='', max_length=300)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
