# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0024_niftimodel_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NiftiModel',
        ),
        migrations.AddField(
            model_name='parametermodel',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='parametermodel',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
