# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0025_auto_20160219_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametermodel',
            name='ExcUnits',
        ),
    ]
