# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0027_parametermodel_nvox'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(default='', max_length=300)),
                ('reqPow', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('reqSS', models.IntegerField(blank=True, default=0, null=True)),
                ('MCP', models.CharField(choices=[('RFT', 'Random Field Theory'), ('BH', 'Benjamini-Hochberg'), ('BF', 'Bonferroni'), ('UN', 'Uncorrected')], max_length=10)),
            ],
        ),
    ]
