# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0028_powermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='KladModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(default='', max_length=300)),
                ('klad', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
