# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0030_auto_20160224_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kladmodel',
            name='SID',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='kladmodel',
            name='klad',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
