# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0033_delete_kladmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermodel',
            name='reqPow',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
