# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0035_parametermodel_alpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametermodel',
            name='maskfile',
            field=models.FileField(default='', upload_to='masks'),
        ),
    ]
