# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0040_auto_20160505_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametermodel',
            name='masklocation',
            field=models.CharField(default='', max_length=300),
        ),
    ]
