# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0043_auto_20160514_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaktablemodel',
            name='err',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
