# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0053_auto_20160914_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermodel',
            name='maskfile',
            field=models.FileField(default='', upload_to='/code/media/maps'),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='spmfile',
            field=models.FileField(default='', upload_to='/code/media/maps'),
        ),
    ]
