# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0059_auto_20170112_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuropowerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(default='', max_length=300)),
                ('step', models.IntegerField(default=0)),
                ('map_url', models.CharField(default='', max_length=300)),
                ('mask_url', models.CharField(default='', max_length=300)),
                ('local_dir', models.CharField(default='', max_length=300)),
                ('map_local', models.CharField(default='', max_length=300)),
                ('mask_local', models.CharField(default='', max_length=300)),
                ('mapID', models.CharField(default='', max_length=300)),
                ('peaktable', models.CharField(default='', max_length=300)),
                ('url', models.URLField(default='')),
                ('location', models.CharField(default='', max_length=300)),
                ('spmfile', models.FileField(default='', upload_to='/var/media/maps')),
                ('masklocation', models.CharField(default='', max_length=300)),
                ('maskfile', models.FileField(default='', upload_to='/var/media/maps')),
                ('nvox', models.CharField(default='', max_length=300)),
                ('ZorT', models.CharField(choices=[('Z', 'Z'), ('T', 'T')], max_length=10)),
                ('Exc', models.DecimalField(decimal_places=4, max_digits=5)),
                ('ExcZ', models.DecimalField(decimal_places=2, default='NaN', max_digits=5)),
                ('DoF', models.DecimalField(decimal_places=2, default='NaN', max_digits=5)),
                ('Subj', models.IntegerField()),
                ('alpha', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('Samples', models.IntegerField(choices=[(1, 'One-sample'), (2, 'Two-sample')])),
                ('SmoothEst', models.IntegerField(choices=[(1, 'Manual'), (2, 'Estimate')], default=1)),
                ('Smoothx', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Smoothy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Smoothz', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Voxx', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Voxy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Voxz', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('err', models.CharField(default='', max_length=1000)),
                ('pi1', models.DecimalField(decimal_places=4, max_digits=10)),
                ('a', models.DecimalField(decimal_places=4, default='NaN', max_digits=10)),
                ('mu', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sigma', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data', picklefield.fields.PickledObjectField(default='', editable=False)),
                ('reqPow', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reqSS', models.IntegerField(blank=True, default=0, null=True)),
                ('MCP', models.CharField(choices=[('RFT', 'Random Field Theory'), ('BH', 'Benjamini-Hochberg'), ('BF', 'Bonferroni'), ('UN', 'Uncorrected')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MixtureModel',
        ),
        migrations.DeleteModel(
            name='ParameterModel',
        ),
        migrations.DeleteModel(
            name='PeakTableModel',
        ),
        migrations.DeleteModel(
            name='PowerModel',
        ),
        migrations.DeleteModel(
            name='PowerTableModel',
        ),
    ]
