# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0060_auto_20170112_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuropowermodel',
            name='mu',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='pi1',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='sigma',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
