# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0061_auto_20170112_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuropowermodel',
            name='local_dir',
        ),
        migrations.RemoveField(
            model_name='neuropowermodel',
            name='mapID',
        ),
        migrations.RemoveField(
            model_name='neuropowermodel',
            name='url',
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='map_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='mask_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='maskfile',
            field=models.FileField(default='', upload_to='/maps'),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='spmfile',
            field=models.FileField(default='', upload_to='/maps'),
        ),
    ]
