# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-13 23:16
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0062_auto_20170112_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuropowermodel',
            name='peaktable',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
