# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0063_auto_20170113_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuropowermodel',
            name='DoF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='Exc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='ExcZ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='Smoothx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='Smoothy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='Smoothz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='Voxx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='Voxy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='Voxz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='alpha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='pi1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='reqPow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='reqSS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuropowermodel',
            name='sigma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
