# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neuropowertoolbox', '0002_auto_20160209_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiftiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField()),
            ],
        ),
    ]
