# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0004_filemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='file',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='niftimodel',
            old_name='file',
            new_name='url',
        ),
    ]
