# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0005_auto_20160217_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.AddField(
            model_name='niftimodel',
            name='location',
            field=models.CharField(default='defaultvalue', max_length=100),
        ),
    ]
