# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0007_auto_20160217_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZorT', models.CharField(choices=[(1, 'Z'), (2, 'T')], default=1, max_length=1)),
                ('ExcUnits', models.CharField(choices=[(1, 'units = p-values (SPM default)'), (2, 'units = t-values (FSL default)')], default=1, max_length=1)),
                ('Exc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Subj', models.IntegerField()),
                ('Samples', models.CharField(choices=[(1, 'One-sample'), (2, 'Two-sample')], default=1, max_length=1)),
                ('Smoothx', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Smoothy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Smoothz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Voxx', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Voxy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Voxz', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='niftimodel',
            name='location',
            field=models.CharField(default='/Users/Joke/Documents/Onderzoek/neuropower/neuropower-dev/neuropower/static_in_pro/our_static/img/zstat1.nii.gz', max_length=300),
        ),
    ]
