# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0008_auto_20160217_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermodel',
            name='ExcUnits',
            field=models.CharField(choices=[(1, 'units = p-values (SPM default)'), (2, 'units = t-values (FSL default)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Samples',
            field=models.CharField(choices=[(1, 'One-sample'), (2, 'Two-sample')], max_length=1),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='ZorT',
            field=models.CharField(choices=[(1, 'Z'), (2, 'T')], max_length=1),
        ),
    ]
