# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0011_niftimodel_sessionkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niftimodel',
            name='sessionKey',
        ),
    ]
