# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0012_remove_niftimodel_sessionkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
