# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0013_peaktablemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='niftimodel',
            name='sessID',
            field=models.CharField(default='', max_length=300),
        ),
    ]
