# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0015_auto_20160217_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niftimodel',
            name='SID',
            field=models.CharField(default='', max_length=300),
        ),
    ]
