# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0023_remove_niftimodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='niftimodel',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
    ]
