# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0026_remove_parametermodel_excunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametermodel',
            name='nvox',
            field=models.CharField(default='', max_length=300),
        ),
    ]
