# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0029_kladmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermodel',
            name='reqPow',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='powermodel',
            name='reqSS',
            field=models.IntegerField(default=0),
        ),
    ]
