# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0032_auto_20160225_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KladModel',
        ),
    ]
