# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0034_auto_20160225_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametermodel',
            name='alpha',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
        ),
    ]
