# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0037_parametermodel_spmfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermodel',
            name='maskfile',
            field=models.FileField(default='', upload_to=b'/var/folders/_w/jhr1_cz536d5tgdjjb6kpxxc0000gn/T'),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='spmfile',
            field=models.FileField(default='', upload_to=b'/var/folders/_w/jhr1_cz536d5tgdjjb6kpxxc0000gn/T'),
        ),
    ]
