# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0037_parametermodel_spmfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametermodel',
            name='mapID',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='parametermodel',
            name='peaktable',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='peaktablemodel',
            name='peaktable',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Exc',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='maskfile',
            field=models.FileField(default='', upload_to='maps'),
        ),
        migrations.AlterField(
            model_name='peaktablemodel',
            name='data',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='powertablemodel',
            name='data',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
        ),
    ]
