# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0038_auto_20160309_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermodel',
            name='mapID',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
