# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0038_auto_20160302_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermodel',
            name='maskfile',
            field=models.FileField(default='', upload_to='maps'),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='spmfile',
            field=models.FileField(default='', upload_to='maps'),
        ),
    ]
