# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0039_auto_20160302_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermodel',
            name='Exc',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
