# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropowertoolbox', '0039_parametermodel_smoothest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermodel',
            name='Smoothx',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Smoothy',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Smoothz',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Voxx',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Voxy',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Voxz',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
